version: '3.9'

volumes:
  mosquito_alert_v1_local_postgres_data: {}

services:
  django:
    build:
      context: .
    image: mosquito_alert_v1_local
    container_name: mosquito_alert_v1_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=tigaserver_project.settings_dev
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"

  postgres:
    image: postgis/postgis:12-3.2
    container_name: mosquito_alert_v1_local_postgres
    volumes:
      - mosquito_alert_v1_local_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    # NOTE: uncomment if want to see all queries in docker logs.
    #command: "-c log_statement=all"
