name: CI

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: ['v2']  # Change to ['master', 'main'] when merged.
    #paths-ignore: ['docs/**']

  push:
    branches: ['v2']  # Change to ['master', 'main'] when merged.
    #paths-ignore: ['docs/**']

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      # Consider using pre-commit.ci for open source project
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0

  # With no caching at all the entire ci process takes 4m 30s to complete!
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Build the Stack
        run: docker compose -f docker-compose-local.yml build

      #- name: Run DB Migrations
      #  run: docker compose -f docker-compose-local.yml run --rm django python manage.py migrate

      - name: Run Django Tests
        # Need to run as root because we are writing the results into the shared volume.
        run: docker compose -f docker-compose-local.yml run -u root --rm django coverage run -m pytest

      - name: Create coverage XML report
        # Need to run as root because we are writing the results into the shared volume.
        run: docker compose -f docker-compose-local.yml run -u root --rm django coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true

      - name: Tear down the Stack
        run: docker-compose -f docker-compose-local.yml down
