name: CI

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: ["master"]

  push:
    branches: ["master"]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgis/postgis:12-3.2
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8.10"
          cache: pip
          cache-dependency-path: |
            requirements/prod_20_04.pip
            requirements/dev.pip

      - name: Apt Update
        run: |
          sudo apt-get update

      - name: Install packages
        run: |
          # https://stackoverflow.com/questions/7496547/does-python-scipy-need-blas
          sudo apt-get -y install gfortran libopenblas-dev liblapack-dev
          # GIS dependencies. See: https://docs.djangoproject.com/en/dev/ref/contrib/gis/install/geolibs/
          sudo apt-get -y install binutils libproj-dev gdal-bin

      - name: Install Dependencies
        run: |
          # Some considerations here:
          #     setuptools<58.0.0 required for anyjson
          #     cython<3.0.0 required for the pyyaml version we are using (https://stackoverflow.com/questions/7496547/does-python-scipy-need-blas)
          pip install --upgrade pip "setuptools<58.0.0" "wheel==0.40.0" "cython<3.0.0"
          pip install numpy==1.23.1  # Solved bug when install scikit. Use same version as dev.pip
          pip install -r requirements/dev.pip

      - name: Run tests
        run: python manage.py test
